project_id = "cntyxxpjoqjncndodcux"

[api]
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320

[db.pooler]
enabled = false

[realtime]
enabled = false

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true

[auth.external.google]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
skip_nonce_check = false
